name: Stable Release
on:
  push:
    branches:
      - 'main'

jobs:
  stable:
    permissions:
      contents: read
      id-token: write
    uses: the-guild-org/shared-config/.github/workflows/release-stable.yml@main
    if: ${{ github.event.pull_request.title != 'Upcoming Release Changes' }}
    with:
      releaseScript: release
      nodeVersion: 22
      packageManager: pnpm
    secrets:
      githubToken: ${{ secrets.GUILD_BOT_TOKEN }}
      npmToken: ${{ secrets.NODE_AUTH_TOKEN }}
